# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-31 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0006_book_current_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, b'\xe6\xad\xa3\xe5\x9c\xa8\xe5\x80\x9f\xe9\x98\x85'), (2, b'\xe5\xb7\xb2\xe7\xbb\x8f\xe5\xbd\x92\xe8\xbf\x98')], default=1, verbose_name=b'\xe5\x80\x9f\xe9\x98\x85\xe7\x8a\xb6\xe6\x80\x81')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('return_at', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
