# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-04-01 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_auto_20190401_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
