# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-21 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_auto_20190401_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.IntegerField(choices=[(1, '\u6b63\u5728\u501f\u9605'), (2, '\u5df2\u7ecf\u5f52\u8fd8')], default=1, verbose_name=b'\xe5\x80\x9f\xe9\x98\x85\xe7\x8a\xb6\xe6\x80\x81'),
        ),
    ]
