# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-21 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_auto_20190521_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
