# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('introduce', models.TextField(blank=True)),
                ('count', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
