# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-31 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20170706_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='current_count',
            field=models.IntegerField(default=0),
        ),
    ]
