# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-21 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_current_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_recommand',
            field=models.BooleanField(default=False),
        ),
    ]
