# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20170702_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(choices=[(1, b'\xe7\xad\x89\xe5\xbe\x85\xe4\xbb\x98\xe6\xac\xbe'), (2, b'\xe7\xad\x89\xe5\xbe\x85\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98\xe7\xa1\xae\xe8\xae\xa4'), (3, b'\xe5\xb7\xb2\xe7\xa1\xae\xe8\xae\xa4\xe6\x94\xb6\xe6\xac\xbe'), (4, b'\xe5\xb7\xb2\xe9\x80\x80\xe6\xac\xbe')], default=1, verbose_name='\u652f\u4ed8\u72b6\u6001'),
        ),
    ]
